[[redirects]]
  from = "/resume"
  to = "https://drive.google.com/file/d/1gTqFOliwgtfZVJSfv4G4d9S4vdxEn0V8/view?usp=sharing"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog_index.html"
  status = 200
  force = true
