[[redirects]]
  from = "/resume"
  to = "https://docs.google.com/document/d/12vsNNYmCKPjM2rUDJ5Q1EVYwviHwoCzYwiYYHApWY10"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog_index.html"
  status = 200
  force = true
