[[redirects]]
  from = "/resume"
  to = "https://drive.google.com/file/d/1VG8v7ZUXrzsJ8WXNC3rLRaduQ8ck8nmj/view?usp=sharing"
  status = 301
  force = true

[[redirects]]
  from = "/blog"
  to = "/blog_index.html"
  status = 200
  force = true
