name: Pandoc Build Site

on:
  schedule:
    - cron: "1 0 * * *"
  push:
  workflow_dispatch:

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout repo content
       uses: actions/checkout@v2 # checkout the repository content to github runner.
     - name: Setup pandoc
       uses: r-lib/actions/setup-pandoc@v1
       with:
         pandoc-version: '2.14.1'
     - name: Setup python3
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
     - name: Execute blog.py script
       run: |
         python blog.py
     - name: Commit changes
       uses: EndBug/add-and-commit@v7
       with:
        author_name: Ben Boyle
        author_email: me@benboyle.ca
        message: 'build site'
        add: './*'
        push: true
